#В миллисекундах
cooldown: 300000

messages:
  heal:
    self: "Вы были исцелены!"
    other:
      #Игрок, который лечит
      sender: "Вы исцелили игрока %player%"
      #Игрок, которого лечат
      target: "Вы были исцелены игроком %player%"
  feed:
    self: "Вы успешно уталили голод!"
    other:
      #Игрок, который кормит
      sender: "Вы накормили игрока %player%"
      #Игрок, которого кормят
      target: "Вы были накормлены игроком %player%"
  no-perms: "У вас нет прав для этой команды!"
  offline: "Игрок не в сети."
  config: "Конфиг успешно перезагружен!"